import type { NextAppProps } from "next/app"
import type { MetadataRoute } from "next/server"

export default function RootLayout({ children }: NextAppProps) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
} as MetadataRoute



import './globals.css'